### ISSUE TITLE
can not make it working...

### ISSUE THREAD

**Issue by wumingque** [Vertabelo/vertabelo-sqlalchemy#3]
Hi, whenever I use the script I have the following error. please advise.
`Traceback (most recent call last):
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 604, in <module>
    main(sys.argv[1:])
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 601, in main
    generate(inputfile,outputfile)
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 574, in generate
    g.process();
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 554, in process
    self.dbModel.build(self.root)
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 259, in build
    t.build(i)
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 151, in build
    c.build(i)
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 98, in build
    pk = subnode_value(xmlNode,"PK")
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 77, in subnode_value
    node = find_subnode_by_name(node,sub_name)
  File "./vertabelo-sqlalchemy/vertabelo_sqlalchemy.py", line 73, in find_subnode_by_name
    raise Exception("couldn't find tag '%s' in '%s'" % (sub_name, node))
Exception: couldn't find tag 'PK' in '<DOM Element: Column at 0x7fae1bb04908>'`

**Comment by nablaone** [comment]
Hi,

Please pull changes from this repo. I've just pushed support for newer version of Vertabelo XML. Please let me know if it works for you.

**Comment by wumingque** [comment]
Hi Rafał,

Sorry about the late reply. It works great now. Thank you so much.

Mingque

**Comment by mathcadd** [comment]
I have this problem too.
