### ISSUE TITLE
Vertabelo XML format 2.4 support

### ISSUE THREAD

**Issue by dwikler** [Vertabelo/vertabelo-sqlalchemy#6]
I am experiencing an issue reporting Vertabelo XML format 2.4 is not supported.
Is this version limited to Vertabelo XML format 2.2?

```console
Traceback (most recent call last):
  File "./vertabelo_sqlalchemy.py", line 764, in <module>
    main(sys.argv[1:])
  File "./vertabelo_sqlalchemy.py", line 761, in main
    generate(inputfile,outputfile)
  File "./vertabelo_sqlalchemy.py", line 731, in generate
    g.process();
  File "./vertabelo_sqlalchemy.py", line 709, in process
    raise Exception("Not supported Vertabelo XML format version %s" % (version))
Exception: Not supported Vertabelo XML format version 2.4
```

**Comment by DUELCHR** [comment]
any news on this Topic?
